# Q1
Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.



In [7]:
import numpy as np
np.vander([1,2,3,4]).

array([[ 1,  8, 27, 64],
       [ 1,  4,  9, 16],
       [ 1,  2,  3,  4],
       [ 1,  1,  1,  1]])

In [42]:
def func(inp_array,N,increasing = False):
    if not increasing:
        op_matrix = np.array([x**(N-i-1)for x in inp_array for i in range(N)]).reshape(inp_array.size,N)
    elif increasing:
        op_matrix = np.array([x**i for x in inp_array for i in range (N)]).reshape(inp_array.size,N)
    return op_matrix

In [43]:
input_array = np.array([1,2,3,4,5])
N = 3
func(input_array,N,False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [45]:
print("The input array is:",input_array,"\n")
print("Number of columns in output matrix should be:",N,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",func(input_array,N,False),"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",func(input_array,N,True),"\n")


The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



# Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [60]:
def moving_average_x(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w

In [61]:
moving_average(input_array,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [59]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
input_array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3
print("The input array is:",input_array,"\n")
print("Moving average sequence be:",N,"\n")
print("Value of Moving Average :\n\n",moving_average(input_array,N),"\n")

The input array is: [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 

Moving average sequence be: 3 

Value of Moving Average :

 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333] 

